print("")

numero_1 = 5
numero_2 = 9
resultado_suma = (numero_1 + numero_2)
resultado_resta = (numero_1 - numero_2)
resultado_multiplicacion = (numero_1 * numero_2)
Resultado_Division = (numero_1 / numero_2)
print("El resultado de la suma es:",resultado_suma)
print("El resultado de la resta es:",resultado_resta)
print("El resultado de la multiplicación es:",resultado_multiplicacion)
print("El resultado de la división es:",Resultado_Division)

print("") 